### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#1]
### Tools
- [ ] Convert html to pug
- [ ] Convert pug to html

### Language service for .vue

|                        |        html        |        pug         |  css / css module  |     js in html     |     js in pug      | ts / js in <script> |
|:-----------------------|:------------------:|:------------------:|:------------------:|:------------------:|:------------------:|:-------------------:|
| Diagnostics            | :heavy_check_mark: |        todo        |        todo        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Formatting             | :heavy_check_mark: |        todo        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Auto completion        | :heavy_check_mark: |        todo        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Type check             | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Quick info             | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Quick comment          |        todo        |        todo        | :heavy_check_mark: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark:  |
| Find .vue definitions  | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Find .vue references   | :heavy_minus_sign: | :heavy_minus_sign: |        todo        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Rename .vue references | :heavy_minus_sign: | :heavy_minus_sign: |        todo        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Find .ts definitions   | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Find .ts references    | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |
| Rename .ts references  | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_minus_sign: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |

### Language service for .ts
- [x] Find .vue references
- [ ] Rename .vue references (Currently unable to resolve, but you can renaming a reference in .vue to get the same result.)
