### ISSUE TITLE
Task list for February to September

### ISSUE THREAD

**Issue by johnsoncodehk** [johnsoncodehk/volar#1237]
- Code Refactoring
  - [x] @volar/vue-language-service (#1009)
  - [x] @volar/vue-typescript (#1004) (#1050) (#1395)
  - [x] @volar/vue-language-server
  - [x] @volar/vue-language-core
- vue-tsc
  - [x] watch mode (#1000)
  - [x] incremental mode (#787)
  - [x] `vueCompilerOptions.*` leave experimental
  - [x] Plugin API for virtual code generation (#185)
- Web IDE Support (#612)
  - [x] Document features
  - [x] Virtual file system
  - [x] Language features
- Documentation
  - [x] High Level System Overview
  - [x] Contribution Guidelines (#1055)
  - [ ] Usage manual
- Optimization
  - [x] Caching TS auto-import (#808)
  - [x] Generate virtual code without type calculation (#455)
  - [x] Minimize extension size (v0.34.10 ~1.5MB)
  - [x] Minimize vue-tsc depends
  - [x] Improve code mapping performance
  - [x] Incremental parser
- Preview
  - [x] Vite + Vue 3 preview
  - [x] Nuxt 3 preview
  - [x] Go to code
  - [x] Highlight dom elements by selected code
  - [x] Release `@volar/preview` (#1115)
  - [x] Component preview for Vite + Vue 3 (#1476)
- Language Server
  - [x] Support custom embedded language plugin
  - [x] VitePress support (#1399)
- Others
  - [ ] Fully type-check tests
  - [x] Move to official publisher (#1124)
  - [ ] Move repo to @vuejs org (#811)
  - [ ] Released v1.0 🎉

---

My goal is finished all the heavy tasks and documentation in ~August~ September to make this project easier maintain by other peoples. Unless the sponsorship goal is met, after ~August~ September I will return to full-time job to make ends meet. But I will still try to maintain in my spare time. 

If you like my work, consider buy me a coffee to give me some encouragement. 💖

**Comment by baixiaoyu2997** [comment]
能否支持一下关闭takeover mode弹窗的功能，每次打开都要提醒一下
